[development]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "maP3g/FB2/CNDRQmA3M+hP+bjDMv1drr/71bGa3aQ5A="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "jiaCiLs7Oa/+4ZXcTotgeIzG2ibfgq0LCZ4hz6mN4DE="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 30
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "R6bIC054KQ+WNrVPqNC5MRTauNqlBHy1xhF8igUVw0I="
limits = { forms = 32768 }
